name: manual_camera_pro
description: A Flutter plugin for manually controlling the camera on Android devices. All the native functions of the Flutter official Camera plugin are available.
version: 0.1.0

homepage: https://afonsoraposo.com
repository: https://github.com/afonsocraposo/manual_camera

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  path_provider: ^2.0.15
  video_player: ^2.6.1
  lints: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.afonsoraposo.camera
        pluginClass: CameraPlugin
      ios:
        pluginClass: CameraPlugin
